# This is a config for E2B sandbox template.
# You can use template ID (37npderjx0pg8vcmypg4) or template name (v0-nextjs-build) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-nextjs-build") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-nextjs-build") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-nextjs-build')

team_id = "fdde37c6-7016-42a4-b0ab-27b2b0b201c2"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-nextjs-build"
template_id = "37npderjx0pg8vcmypg4"
